service: opensearch-nodejs-dive-in
provider:
  name: aws
  region: ${self:custom.region}
custom:
  stage: ${opt:stage, self:provider.stage}
  region: eu-west-1
  domain: demo-${opt:stage}
resources:
  Resources:
    OpenSearchDomain:
      Type: AWS::OpenSearchService::Domain
      Properties:
        DomainName: ${self:custom.domain}
        EngineVersion: 'OpenSearch_2.3'
        ClusterConfig:
          # DedicatedMasterEnabled: true
          InstanceCount: '1'
          # ZoneAwarenessEnabled: true
          InstanceType: 't3.small.search'
          # DedicatedMasterType: 't3.small.search'
          # DedicatedMasterCount: '1'
        EBSOptions:
          EBSEnabled: true
          VolumeSize: '20'
          VolumeType: 'gp3'
        AccessPolicies:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS: '*'
              Action: 'es:*'
#              Action: [
#                "es:ESHttpGet",
#                "es:ESHttpPut"
#              ]
              Resource: "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${self:custom.domain}/*"
        AdvancedOptions:
          rest.action.multi.allow_explicit_index: true